dependencies:
  - python=3.9.2
  - pip:
    - spacy
    - ipykernel
    - scipy
    - numpy
    - scikit-learn
    - matplotlib
    - pandas
    - thinc
    - pygame
    - pyttsx
    - pyinstaller
    - requests
    - python-docx
    - scrapy
    - beautifulsoup4
    - django
    - flask
